name: Docker CI/CD

on:
  push:
    branches:
      - main # Specify the branch you want to trigger the pipeline on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    - name: Build and Push Docker Image
      run: |
        docker buildx build --file Dockerfile -t <your-dockerhub-username>/<image-name>:latest .
        docker buildx imagetools create <your-dockerhub-username>/<image-name>:latest
        docker push <your-dockerhub-username>/<image-name>:latest
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
